name: fan_light
description: "A new Flutter project."

publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.2.beta

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  http: ^1.4.0
  get: ^4.7.2
  flutter_screenutil: ^5.9.3
  multicast_dns: ^0.3.3
  permission_handler: ^11.0.1
  shared_preferences: ^2.5.3
  flutter_background_service: ^5.1.0
  android_alarm_manager_plus: ^4.0.7
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: main
      path: workmanager







dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
